### ISSUE TITLE
-bash: hl: command not found

### ISSUE THREAD

**Issue by redscience** [mbornet-hl/hl#12]
I used this command:
git clone http://github.com/mbornet-hl/hl
but when I want to use it in my command, I see this error message:
df -h | hl --df
-bash: hl: command not found

**Comment by redscience** [comment]
How can I do this?

**Comment by mbornet-hl** [comment]
To compile the program, go to the sources directory, and run the make 
command :
     cd src
     make
To put the binary in a directory of your PATH variable, display your 
PATH variable, choose an appropriate directory and copy the hl binary in 
the directory you choose :
     echo $PATH
     cp hl $HOME/bin/hl
or :
     cp hl /usr/local/bin/hl
