### ISSUE TITLE
Comparison with supercat?

### ISSUE THREAD

**Issue by dufferzafar** [mbornet-hl/hl#13]
Hi, I use supercat for doing the highlighting: http://supercat.nosredna.net/

It is also written in C (& uses regcomp) etc.

Have you compared your tool against it, and if so, what are the benefits? (if any) 

Knowing this will be helpful for people (who don't know much C) but want to decide which tool to use.

Thanks!

**Comment by mbornet-hl** [comment]
Hi,

thank you for your mail. I didn't know "supercat".
I've just had a quick look on it and I already see some differences :
- supercat is able to generate HTML colors while hl only generates 
colors for a terminal (it has mainly been designed to colorize text 
files or commands' output),
- supercat distinguishes fixed strings and regex, while hl only treats 
regex, as long as I remember (even if the user specifies fixed strings, 
i.e. with no meta-characters),
- it seems that supercat uses several configuration files while hl needs 
none to work : there are two known configuration files (/etc/default/hl 
and $HOME/.hl.cfg, the configurations in the 2nd one override those in 
the 1st one), and you can select configuration using their name (for 
example : hl --diff, ou : hl --IP --MAC --IPv6), but you may use hl with 
command line options only,
- hl may be used to transparently colorize commands' output (i.e. you 
can type commands as you are used to do, but their output will 
nonetheless be colorized), while supercat doesn't seem to be able to do 
so (for what I've read about it in the documentation),
- hl may colorize differently standard output (stdout) and standard 
error output (stderr), using a specific configuration for each of them, 
while supercat doesn't,
- hl is able to colorize text between two markers specified with regexp, 
so you can, for example, colorize text between <foo> and </foo>, or 
between '{' and '}', and so colorize lines of text containing no 
matching regular expressions as long as these lines are encountered 
after the beginning marker,
- hl has been conceived with the Unix philosophy in mind : simplicity of 
use, interconnection via pipes, a general configuration file for all 
users, which may be overridden by a user's specific configuration,
- I also understand (but I may be wrong) that the colorization used by 
supercat depends on the name of the file's extension or on the file or 
directory name, while the way hl colorizes only depends on explicit 
configurations or option arguments,
and that's all I see for the moment.

I greatly appreciate the fact that the authors created a man page, and 
included some examples : that's also part of the Unix philosophy, and I 
thank them a lot for that !

Now, regarding what command that users will use if they have to use only 
one of these two commands (but why would they have to ???), I can't give 
you an answer : users must try both commands and then they will use the 
one that suits their needs, or the one they prefer.
There probably will be two different populations of users depending on 
their needs and on their feeling with the command line interface of the 
commands.

Regards.

Martial Bornet

**Comment by dufferzafar** [comment]
Thanks a lot for the detailed reply @mbornet-hl

hl does seem to have a lot of features that I want, so I'll soon be porting my 

> hl may be used to transparently colorize commands' output

 How can this be configured exactly?

> hl is able to colorize text between two markers specified with regexp

Yeah, I was actually trying hard to get something like this to work with supercat.

**Comment by mbornet-hl** [comment]
Hello,
sorry for the late answer.
I described the "hl" command in the french magazine "Linux Pratique" number 093 : https://connect.ed-diamond.com/Linux-Pratique/LP-093/Colorisez-vos-textes-avec-la-commande-hl and you can find how to transparently colorize commands in paragraph 14 : Colorisation facile de commandes choisies (script hl_generic).
In simple words,if you want to colorize a command, say "vmstat" for example, you just have to define an "hl" configuration named "vmstat" in $HOME/.hl.cfg, create a hard link named "vmstat" to $HOME/hl_bin/hl_generic, make sure $HOME/hl_bin comes before the directory containing "vmstat" in your PATH variable, and eventually run "hash -d vmstat". That's it. Further calls of "vmstat" should first call $HOME/hl_bin/hl_generic which will call "vmstat" and colorize it.
If you create interesting colorization configurations for Linux commands, I may integrate them in the /etc/default/hl configuration file.
Have fun !
