### ISSUE TITLE
hl script removes itself from PATH and then calls hl...

### ISSUE THREAD

**Issue by dfaure-kdab** [mbornet-hl/hl#15]
How is this supposed to work?

```
$ cd /d/more/src/tools/hl/hl_bin
$ export PATH=$PWD:$PATH
$ df
/d/more/src/tools/hl/hl_bin/df: line 48: hl: command not found
$ which hl
/d/more/src/tools/hl/hl_bin/hl
```

The hl script does:
```
PATH="$(echo "$PATH" | sed "s|^$dirname:||;s|:$dirname:|:|g")"
export PATH
```

**Comment by mbornet-hl** [comment]
The presence of an "hl" script in the hl_bin directory was a mistake : I removed it.
The "df" script from the hl_bin directory is a link to the hl_generic script, which calls the original command ("df") and pipes its standard output and standard error output to two hl commands (via named pipes). So the output of the original "df" command is colorized with "hl --df".

**Comment by dfaure-kdab** [comment]
In a git checkout, "df" and friends are not symlinks, but actual files.
Maybe it would be better to create those symlinks in the Makefile.

**Comment by mbornet-hl** [comment]
Since version 1.93, you can use **hl** without having to install it. You can configure **module** to update PATH, HL_CONF and HL_CONF_GLOB to suit your needs. You can leave the hl top directory wherever you want.
