### ISSUE TITLE
Undefined reference to yyin and yylex but flex is installed

### ISSUE THREAD

**Issue by ASL07** [mbornet-hl/hl#16]
Hi, thanks for your great tool!

I am having some errors compiling on Ubuntu server. Hope you can have a look:

OS version
```bash
uname -a
Linux  4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I have installed flex package version  2.6.4
```bash
lex -V
flex 2.6.4
```

But I get the following errors when running make:
```bash
make[1]: Entering directory '/usr/src/hl/src'
cr_main.o: In function `cr_read_config_file':
cr_main.c:(.text+0x182): undefined reference to `yyin'
cr_main.c:(.text+0x189): undefined reference to `yyin'
cr_main.c:(.text+0x1e2): undefined reference to `yylex'
collect2: error: ld returned 1 exit status
Makefile:18: recipe for target 'hl' failed
make[1]: *** [hl] Error 1
make[1]: Leaving directory '/usr/src/hl/src'
Makefile:6: recipe for target 'hl' failed
make: *** [hl] Error 2
```

Thanks

**Comment by mbornet-hl** [comment]
Hi,
I'm glad you appreciate this command, thanks for your message.

I've just compiled **hl** in an Ubuntu VM (19.10) using flex 2.6.4, and I had not problem to compile it :
mb@vm-ubuntu-19:~/hl/src$ make
cc    -c -o cr_main.o cr_main.c
cc    -c -o cr_gpri.o cr_gpri.c
lex  -t cr_lex.l > cr_lex.c
cc    -c -o cr_lex.o cr_lex.c
./hl: version 1.93

Do you have additional error messages to give me that could better show the problem you encounter ?
Thanks.

**Comment by mbornet-hl** [comment]
Hi, 
do you still have problems with the compilation, or may I close this issue ?

**Comment by mbornet-hl** [comment]
Hi,
it's been more than one month now that I answered your mail.
Since I've got no more message from you, I close this issue.
If you need additional information, feel free to re-open it.
Thanks.
Regards,

Martial
