### ISSUE TITLE
input in flex scanner failed when using configs

### ISSUE THREAD

**Issue by sjaks** [mbornet-hl/hl#19]
When using the predefined configs, I get:
```
sami@pad:~ $ hl -V
hl: version 1.93
sami@pad:~ $ hl --du
input in flex scanner failed
sami@pad:~ $ hl --log_d
input in flex scanner failed
sami@pad:~ $ cat /var/log/auth.log | hl --log
input in flex scanner failed
sami@pad:~ $
```

Version number is visible above.

I'm on Ubuntu 20.04. Feel free to ask if you need to know other package versions. I am eager to help!

**Comment by mbornet-hl** [comment]
Hello,
can you please provide the version numbers for flex and bison ?
You also may use the "-L" option to activate lex (flex) debug and the "-v" option (-v, -vv, -vvv) to get additional information.
Thanks.

**Comment by sjaks** [comment]
I used the debian package discussed in https://github.com/mbornet-hl/hl/issues/17.

**Comment by nfwscho** [comment]
Hi.

I had same problem. What I did is below in terminal, then it worked!

export HL_CONF="/etc/default/hl"
export HL_CONF_GLOB="hl_*.cfg:hl.cfg:.hl_*.cfg:.hl.cfg"
export HL_DEFAULT="3Y"
export HL_A1="2B"
export HL_A2="1n"

Not only HL_CONF but set all environment variables.
add them .bashrc. good luck~

**Comment by mbornet-hl** [comment]
Hi,
I've just installed Ubuntu 20.04 in a VM, downloaded git, make, gcc, flex and bison and it worked fine.
Regarding your problem, I didn't define the configurations you want to use : 
```
mb@VM-ubuntu-20-04:~/projets/hl/config_files$ grep '^du[        ]*:' *
mb@VM-ubuntu-20-04:~/projets/hl/config_files$ grep '^log[       ]*:' *
```
Where do these configurations come from ?

Regards.

**Comment by mbornet-hl** [comment]
I have no answer to the question I asked 25 days ago, so I close this issue.
