### ISSUE TITLE
hl for AIX

### ISSUE THREAD

**Issue by dwizzdonowin** [mbornet-hl/hl#2]
hl can be used on aix.
you must add a line in the makefile
CC=gxlc
and in the cr_cpri.h can you add the 
 \# ifdef FALSE
\# undef FALSE
\# endif
before
\# define FALSE (0)
and
\# ifdef TRUE
\# undef TRUE
\# endif
before
\# define TRUE (0)

the include file getopt.h don't exist on the aix but you can copy it from linux and it work

**Comment by mbornet-hl** [comment]
I pushed a new version of the files : hope there's no compilation problem on AIX (which version do you use, by the way ?), I don't have any access to AIX at the present time.

**Comment by dwizzdonowin** [comment]
I test on an AIx 7.1 with the xlc 12.1
