### ISSUE TITLE
Issue: Cannot compile on macOS

### ISSUE THREAD

**Issue by gspannu** [mbornet-hl/hl#25]
The source does not compile on macOS. Errors attached in the log file [here](https://github.com/mbornet-hl/hl/files/10911322/error.log).
Compiling it on  _macOS 13.2.1 on a M2 MacBook_

However, as suggested by [j16sdiz](https://github.com/j16sdiz) I was **able to compile** on macOS by 
removing the `#define _POSIX_C_SOURCE` from cr_main.c ...

Now, The utility works but **it does not have any of the included configurations**:

Running `hl -H` returns:
 ```
...........
...........
-P  : display configuration(s) matching regexp
-x  : display options count for each config (with -vH options)
Configurations :
```

**Could you please update the code so that it compiles on macOS?
Many thanks...**

Or is it that I am using the configurations incorrectly?
Are these compiled into the hl binary file itself or do I need to place the hl_bin folder in a specific location to get the configurations to work?

**Comment by mbornet-hl** [comment]
Hello,
I fixed compilation problems on macOS. I think it should be fine now : 
```
make clean; make
gcc    -c -o cr_main.o cr_main.c
gcc    -c -o cr_gpri.o cr_gpri.c
lex  -t cr_lex.l > cr_lex.c
gcc    -c -o cr_lex.o cr_lex.c
./hl: version 1.160
```

**Comment by gspannu** [comment]
Compilation on macOS now **does not throw any errors**, however it _still does not include any of the configurations_.
Reported in https://github.com/mbornet-hl/hl/issues/23#issuecomment-1464639792

**Comment by mbornet-hl** [comment]
This issue seems to be the same as[ #23](https://github.com/mbornet-hl/hl/issues/23) and the compilation problem on macOS has been solved, so could you please continue posting on issue #23 ?
I close this one.
Thanks.
