### ISSUE TITLE
OSX port

### ISSUE THREAD

**Issue by codenet** [mbornet-hl/hl#5]
This looks very useful. Do you plan to port it to OSX?

**Comment by mbornet-hl** [comment]
I'm glad that you like this command.
I'm not against porting hl to OSX but I have no Apple computer. If you do have one and want to try to compile it, I can help you to port it if you send the error messages to me.

**Comment by mbornet-hl** [comment]
Hi,
I successfully compiled the code on OS/X just by removing the "inline" keyword in front of the definitions of the functions cr_clear_marker_flags() and cr_same_colors().
So you should be able to compile it easily.
Regards.
