### ISSUE TITLE
hl_bin issue

### ISSUE THREAD

**Issue by leoheck** [mbornet-hl/hl#6]
What is the ``hl_bin/hl``. It makes my system (Ubuntu 16.04) break. I think it calls it forever... maybe hl binary should be renamed to hl_prog (or something) while this script should be the real hl. What you think?

**Comment by mbornet-hl** [comment]
Hi,
the hl_bin directory contains a generic script (hl_generic) on which you can create hard links if you want to colorize the output of commands.
For example, suppose you have a command "foo" whose output you want to colorize : what you have to do is create a configuration named "foo" in your $HOME/.hl.cfg file, then create a hard link named "foo" on "hl_generic": 
     cd $HOME/hl_bin; ln hl_generic foo
and be sure that the directory $HOME/hl_bin comes before the directory containing the "foo" command in your PATH variable.
Then when you type "foo", the shell  launches $HOME/hl_bin/foo which is in fact the hl_generic script, which launches "foo | hl --foo". Thus the output of the "foo" command is colorized without having to explicitly type " | hl --foo".
Regards.
