### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by leoheck** [mbornet-hl/hl#7]
Hi, can you help me with the setup? 
I am trying some of your commands like, but I am having ``input in flex scanner failed`` error.

```
$> df -h | hl --df
input in flex scanner failed
```

**Comment by leoheck** [comment]
Good, I figured out, I had some configs out of the place. This tool is really awesome.

**Comment by mbornet-hl** [comment]
Hi,
you must be careful when you add or modify one of the two configuration files : I recommend that you always use single quotes around the regular expressions you use, and that you first check the validity of their syntax on the command line.
I'm glad if this tool can help you, and if you enjoy using it.
Thanks.
Regards.
