### ISSUE TITLE
hl binary is compiled with profiling enabled

### ISSUE THREAD

**Issue by dfaure-kdab** [mbornet-hl/hl#8]
Every time I launch tools/hl/bin/1.62/amd/debian/7.8/hl, a file called "gmon.out" is generated in the current directory.
Please provide binaries which are _NOT_ compiled with profiling enabled (i.e. without the -pg compile flag, iirc)

**Comment by mbornet-hl** [comment]
Hi David,
that's right, I forgot to remove this option. I'll do it as soon as I can, I'm very busy at the moment.

**Comment by mbornet-hl** [comment]
The last version is compiled with profiling disabled.
