### ISSUE TITLE
Easier installation

### ISSUE THREAD

**Issue by dfaure-kdab** [mbornet-hl/hl#9]
Please provide a toplevel Makefile which recurses to the src dir, a "make install" rule which copies hl into PREFIX/bin, and copies the default config file into a default location where it will be picked up. It could also suggest to add hl/hl_bin to the PATH by adding one line to .bashrc or .zshrc. This would make it easier to get started with hl.

**Comment by mbornet-hl** [comment]
Hi David,
thanks for your comments. Same answer than for issue #8 : I'll do it as soon as I can, I'm very busy at the moment.

**Comment by mbornet-hl** [comment]
A top level Makefile has been added, but it does not copy the hl command into a target directory. It would be better to create an RPM or debian package, but I have no time for this. If someone wants to do it, he's welcome !

**Comment by dfaure-kdab** [comment]
RPM and debian packages rely on `make install`, so that's a first step you'll need anyway :)
